### ISSUE TITLE
lxml.etree.XMLSyntaxError: internal error: Huge input lookup

### ISSUE THREAD

**Issue by kmacbbrewin** [jasonrollins/shareplum#12]
Hello, 
First, this project has been very useful right out of the box for most of my sites.  Thanks!  

I am having one issue with a site I work with frequently, that prevents use of shareplum: 

When trying to access a site with a very large user table, I get the below error from the GetUsers function on line 197 of shareplum.py.  Seems like this may need an additional parser?  

lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 45149, column 647

**Comment by jasonrollins** [comment]
That's an interesting problem.  Are you using Python 2 or 3?  How many users do you have for one site?  I suppose we could include some check for a large response to the User table and try to break up the request into smaller chunks using the query functionality.

**Comment by kmacbbrewin** [comment]
I am using Python 3.6.  We have 50k+ items in the Userinfo table, and the function breaks at 45149. 
 Not quite sure what's special about that number.  I am still kind of new Python and tried to create a parser, but couldn't quite figure it out and implement it with Shareplum.  How would you use the query functionality to break it up?

**Comment by larrys** [comment]
I have a fix here: https://github.com/larrys/shareplum/commit/717c9e3157614b58b2d8145c4e11ce428b37114a

I've been meaning to work on some pull requests with some fixes I've made over the last year of me using this.

**Comment by jasonrollins** [comment]
It looks like Larry has a solution.  

Kenny, would it be possible for you to try it out?  I don't have access to any tables this large to try it out.  

Larry, can you submit a pull request?  Does the large xml parser run slower?

**Comment by larrys** [comment]
I've created #13 that will make it configurable by the user if they want to use huge_tree or not. I've not done any profiling, so I updated my code to make it user driven, and default to existing behavior and not use it.

**Comment by kmacbbrewin** [comment]
I tried these changes, but now the error is different.  These changes still work on sites with a small user table, but still not on a large one.  I am getting a KeyError on ImnName.  What is this field?  I looked at the schema for UserInfo, and I don't see a similar named filed.

Here's the error now: 
File "/checklist_env/lib/python3.6/site-packages/shareplum/shareplum.py", line 204, in <dictcomp>
    return {'py': {i['ImnName']: i['ID']+';#'+i['ImnName'] for i in data},
KeyError: 'ImnName'

**Comment by larrys** [comment]
Are you able to run this in something that has a debugger, and put a breakpoint on that line, and see what the data looks like in the data variable? My list of users has a ImnName field.

**Comment by kmacbbrewin** [comment]
Looks like it depends on which version of SharePoint is being used.  In older versions the field is simply "Name"  in newer versions, it's "ImnName".  

I was able to create a connection to the problem site and create a list.  Thanks for your help! 

Now, to figure out the update list items and update list functionality.  

Have either of you solved for updating a list (e.g. adding columns and specifying type)?  I believe that is part of the updatelist SharePoint api, but I see that was still a Todo item.

**Comment by kmacbbrewin** [comment]
Also, a different question: What's the preference/etiquette on this project?  Should I close the issue now or should we wait until the pull request is complete

**Comment by jasonrollins** [comment]
I don't have any desired etiquette.  Thanks for your interest.  I have not had much of a chance to work on it for some time.  That will hopefully change soon.  You can just leave it open for now as a reminder for me until I merge in a fix.  Which versions of SharePoint are you using SharePlum with?

**Comment by kmacbbrewin** [comment]
I have successfully tested it on SP 2010 and SP2013 on prem servers.  I may also try to use it on an O365 instance, but I think the authentication is different.

**Comment by ldacey** [comment]
The fix from larrys worked for me as well. I manually edited the py shareplum.py file.

**Comment by mahesh557** [comment]
Thanks larry. it worked for me.
Replaced all `envelope = etree.fromstring(response.text.encode('utf-8'))`
to           `envelope = etree.fromstring(response.text.encode('utf-8'), parser=etree.XMLParser(huge_tree=True))`

**Comment by jasonrollins** [comment]
I'm closing this for now.  Please open another issue if it still isn't working.

**Comment by eshwarsachin** [comment]
@kmacbbrewin Hi, 

I have the same `KeyError: 'ImnName'` 

Could you please help me with the resolution?
